Completed javascript-ajax exercise
sanfordhuynh/m2-1023-code-solutions pull request #9
Opened 2023-10-31 04:01 UTC by sanfordhuynh

2023-11-01 01:16 UTC, ninajhun requested changes
Can you add a screenshot so I can confirm you received the correct data

2023-11-01 01:16 UTC, ninajhun commented on javascript-ajax/users.js
> +xhr.open('GET', ' https://jsonplaceholder.typicode.com/users' + name);
I don't see any data here when I test this URL^  "https://jsonplaceholder.typicode.com/usersname

The correct URL is: `https://jsonplaceholder.typicode.com/users`

2023-11-01 01:36 UTC, sanfordhuynh commented
![fetch](https://github.com/sanfordhuynh/m2-1023-code-solutions/assets/16739580/395dba3d-f89f-4db6-9888-48197bfea4af)

2023-11-03 03:38 UTC, ninajhun approved these changes

2023-12-15 02:55 UTC, merged